name: Test Connection
on: [push] # Körs varje gång du pushar kod

jobs:
  test-runner:
    runs-on: self-hosted # <--- Signalen till din server
    steps:
      -  name: Validera konfigurationen (Dry Run)
        # Detta kollar bara om filen är korrekt skriven, men startar inget!
        run: docker compose config
